### ISSUE TITLE
net11

### ISSUE THREAD

**Issue by imrepentek** [impexeris/DiY-Arduino-Geiger-Counter-SMD#1]
Hi,

I can't see where this "net11" connects to:

https://github.com/impexeris/DiY-Arduino-Geiger-Counter-SMD/blob/master/Circuit%20Schematics/LCD%20contrast%20and%20brightness%20controls.pdf

thanks for the fix/clarification in advance.

Imre

**Comment by impexeris** [comment]
it connects to the pin 16 of the display DS1
![Screen Shot 2019-10-09 at 22 31 44](https://user-images.githubusercontent.com/24243985/66513885-b9abd500-eae4-11e9-92e6-bc586ce69ed7.png)
